name: Kahani Duniya Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python files
        run: |
          python -m py_compile main.py
          python -m py_compile content_tools.py

      - name: Run main.py
        run: python main.py
